### ISSUE TITLE
Azure Static Web Apps Deployment Setup Instructions

### ISSUE THREAD

**Issue by timponce** [bsul24/CS467_PAW_MailMerge#15]
# Instructions for Deploying React Application to Azure Static Web Apps

## Proof of Concept
- https://red-bay-04e9db11e.5.azurestaticapps.net
- https://github.com/timponce/CS467_PAW_MailMerge_Fork

## Prerequisites
- Admin privileges on the GitHub repository
- Azure account with subscription access
- Node.js installed locally

---

### 1. Fix Linting Issues
- Remove unused variables in `App.jsx`:
  - Remove the `logo` import and unused state variables `csvData` and `generatedEmails`.

---

### 2. Add Required Babel Plugin
- Add the following to `frontend/package.json` under `devDependencies`:

```json
{
  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
  }
}
```

### 3. Azure Portal Setup

1. Log into Azure Portal.
2. Click **"Create a resource"**.
3. Search for **"Static Web App"**.
4. Fill in basic details:
   - **Resource Group**: Create a new one or use an existing one.
   - **Name**: `paw-mailmerge` (or preferred name).
   - **Hosting Plan**: Free.
   - **Region**: Select nearest to your users.
5. Click **"Sign in with GitHub"**.
6. Select:
   - **Organization**: Your GitHub organization.
   - **Repository**: `CS467_PAW_MailMerge`.
   - **Branch**: `main`.
7. In **Build Details**:
   - **Build Presets**: React.
   - **App location**: `/frontend`.
   - **Output location**: `build`.
8. Review and click **Create**.
9. Wait for the resource to be created.

---

### 4. GitHub Workflow Setup

Create a file `.github/workflows/azure-static-web-apps.yml` with the following content:

```yaml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    uses: Azure/static-web-apps-deploy@v1
    with:
      azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
```

### 5. Configure GitHub Secrets

1. Go to the repository **Settings**.
2. Navigate to **Secrets and variables → Actions**.
3. Add a new repository secret:
   - **Name**: `AZURE_STATIC_WEB_APPS_API_TOKEN`
   - **Value**: (Copy from Azure Portal → Your Static Web App → Overview → **Manage deployment token**)

---

### 6. Verification

1. Push changes to the `main` branch.
2. Check the **GitHub Actions** tab for deployment status.
3. Once complete, access your app at the URL provided in the Azure Portal.

---

## Blocker

⚠️ **Admin privileges on the GitHub repository are required** to:
- Configure GitHub Actions.
- Add repository secrets.
- Set up GitHub-Azure integration.

Please ensure you have the necessary permissions before starting this process.

---

## Additional Notes

- The deployment URL will be in the format: `https://{your-site-name}.azurestaticapps.net`.
- Monitor deployments in the **GitHub Actions** tab.
- Check the Azure Portal for resource status and logs.
